# Generated by Django 4.0.3 on 2022-03-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='admin', max_length=40)),
                ('contact', models.CharField(max_length=15, null=True)),
                ('age', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('father', models.CharField(max_length=40, null=True)),
                ('city', models.CharField(default='Lucknow', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='MATH101', max_length=10)),
                ('name', models.CharField(default='Mathematics', max_length=20)),
                ('description', models.CharField(max_length=100,null=True)),
                ('instructor', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
